name: app_builder
description: "Build tools for Android apps."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.11.0
  path: ^1.9.0
  collection: ^1.18.0
  shared_preferences: ^2.3.1
  file_selector: ^1.0.3
  fluent_ui: ^4.9.1
  window_manager: ^0.4.0
  system_theme: ^3.0.0
  go_router: ^14.2.3
  rxdart: ^0.28.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
