name: app_builder
description: "Build tools for Android apps."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.11.0
  path: ^1.9.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  file_selector: ^1.0.3
  fluent_ui: ^4.8.6
  window_manager: ^0.3.8
  system_theme: ^2.3.1
  go_router: ^13.2.0
  rxdart: ^0.27.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
