name: task_repository
description: A repository that manage build tasks.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  path: ^1.9.0
  storage:
    path: ../storage/storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.0
  very_good_analysis: ^7.0.0
